using KoobecaFeedController.BL.Request;

namespace KoobecaFeedController.BL.Handlers
{
    internal class GetDashboardMenusHandler : ActivityHandler
    {
        

        public GetDashboardMenusHandler(uint userId, RequestParams reqParams) : base(userId, reqParams)
        {

        }

        public override void Execute()
        {
            Response = @"{
   ""menus"":[ 
      { 
         ""name"":""home"",
         ""type"":""menu"",
         ""label"":""Home"",
         ""headerLabel"":"""",
         ""module"":""core"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":"""",
         ""memberView"":1
      },
      { 
         ""name"":""spread_the_word"",
         ""type"":""menu"",
         ""label"":""Spread the Word"",
         ""headerLabel"":""Spread the Word"",
         ""module"":null,
         ""color"":"""",
         ""icon"":""f045"",
         ""url"":""""
      },
      { 
         ""name"":""core_main_user"",
         ""type"":""menu"",
         ""label"":""Members"",
         ""headerLabel"":"""",
         ""module"":""user"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":"""",
         ""memberViewType"":""1""
      },
      { 
         ""name"":""core_main_friends"",
         ""type"":""menu"",
         ""label"":""Friends"",
         ""headerLabel"":""core_main_friends"",
         ""module"":""user"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":""""
      },
      { 
         ""name"":""core_main_album"",
         ""type"":""menu"",
         ""label"":""Albums"",
         ""headerLabel"":"""",
         ""module"":""album"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":"""",
         ""memberView"":1,
         ""canCreate"":{ 
            ""default"":1,
            ""photo"":0
         }
      },
      { 
         ""name"":""core_main_sitegroup"",
         ""type"":""menu"",
         ""label"":""Groups"",
         ""headerLabel"":""Groups"",
         ""module"":""sitegroup"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":"""",
         ""memberView"":1,
         ""canCreate"":{ 
            ""default"":1,
            ""packagesEnabled"":0
         }
      },
      { 
         ""name"":""core_main_sitepage"",
         ""type"":""menu"",
         ""label"":""Pages"",
         ""headerLabel"":""Pages"",
         ""module"":""sitepage"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":"""",
         ""memberView"":1,
         ""canCreate"":{ 
            ""default"":1,
            ""packagesEnabled"":""0""
         }
      },
      { 
         ""name"":null,
         ""type"":""category"",
         ""label"":""Help & Settings"",
         ""headerLabel"":"""",
         ""module"":null,
         ""color"":"""",
         ""icon"":"""",
         ""url"":""""
      },
      { 
         ""name"":""contact_us"",
         ""type"":""menu"",
         ""label"":""Contact Us"",
         ""headerLabel"":"""",
         ""module"":""core"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":""""
      },
      { 
         ""name"":""user_settings"",
         ""type"":""menu"",
         ""label"":""Settings"",
         ""headerLabel"":"""",
         ""module"":""user"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":""""
      },
      { 
         ""name"":""terms_of_service"",
         ""type"":""menu"",
         ""label"":""Terms of Service"",
         ""headerLabel"":"""",
         ""module"":""core"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":""https://beta.koobeca.com/help/terms""
      },
      { 
         ""name"":""privacy_policy"",
         ""type"":""menu"",
         ""label"":""Privacy Policy"",
         ""headerLabel"":"""",
         ""module"":""core"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":""https://beta.koobeca.com/help/privacy""
      },
      { 
         ""name"":""core_multi_languages"",
         ""type"":""menu"",
         ""label"":""Multi Languages"",
         ""headerLabel"":null,
         ""module"":null,
         ""color"":"""",
         ""icon"":"""",
         ""url"":""""
      },
      { 
         ""name"":""signout"",
         ""type"":""menu"",
         ""label"":""Sign Out"",
         ""headerLabel"":"""",
         ""module"":""user"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":""""
      },
      { 
         ""name"":""core_main_rate"",
         ""type"":""menu"",
         ""label"":""Rate us"",
         ""headerLabel"":""Rate us"",
         ""module"":""core"",
         ""color"":"""",
         ""icon"":"""",
         ""url"":""""
      }
   ],
   ""languages"":{ 
      ""default"":""en"",
      ""languages"":{ 
         ""en"":""English""
      }
   },
   ""location"":""0"",
   ""memberViewType"":""1"",
   ""app_tour"":""0"",
   ""isOTPEnable"":0,
   ""isShowAppName"":0,
   ""showFilterType"":""1"",
   ""storyDuration"":""1"",
   ""is_show_greeting_announcement"":""1"",
   ""restapilocation"":{ 
      ""locationType"":""notspecific"",
      ""autodetectLocation"":""0"",
      ""isChangeManually"":""0""
   },
   ""seaolocation"":{ 
      ""locationType"":""notspecific""
   },
   ""browse_as_guest"":""0"",
   ""isFavouriteEnable"":0,
   ""video_quality"":""0"",
   ""isChannelEnable"":1,
   ""isPlaylistEnable"":1,
   ""canSendMessage"":""everyone"",
   ""allowTargetPost"":1,
   ""allowSchedulePost"":1,
   ""allowfeelingActivity"":1,
   ""allowAdvertize"":0,
   ""allowPin"":1,
   ""allowGreeting"":1,
   ""allowMemories"":1,
   ""allowBanner"":1,
   ""isPrimeMessengerActive"":""1"",
   ""isSitestoriesEnable"":1,
   ""enable_modules"":[
      ""activity"",
      ""advancedactivity"",
      ""album"",
      ""announcement"",
      ""authorization"",
      ""core"",
      ""facebookse"",
      ""facebooksepage"",
      ""facelight"",
      ""fields"",
      ""invite"",
      ""koobeca"",
      ""messages"",
      ""nestedcomment"",
      ""network"",
      ""payment"",
      ""primemessenger"",
      ""seaocore"",
      ""sitealbum"",
      ""siteandroidapp"",
      ""siteapi"",
      ""sitecontentcoverphoto"",
      ""sitecore"",
      ""siteevent"",
      ""sitefaq"",
      ""siteforum"",
      ""sitegroup"",
      ""sitegroupalbum"",
      ""sitegroupmember"",
      ""sitegroupvideo"",
      ""sitehashtag"",
      ""siteiosapp"",
      ""sitelogin"",
      ""sitepage"",
      ""sitepagealbum"",
      ""sitepagebadge"",
      ""sitequicksignup"",
      ""sitereaction"",
      ""sitestories"",
      ""sitetagcheckin"",
      ""sitevideo"",
      ""storage"",
      ""suggestion"",
      ""user""
   ]
    }
";
        }


    }
}